version: "3.8"
services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tqshw1
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
    - "3306:3306"
    volumes:
      - db_file:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./backend/
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/tqshw1
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect

  frontend:
    build: ./frontend
    ports:
      - 3030:3030
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yaml

    volumes:
    - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./config/grafana:/etc/grafana/provisioning/

volumes:
    db_file:
    frontend: